// Reads the generated card illustrations (assets/cards/<id>.png) and extracts each character's hair colour and
// jacket colour so the 16×28 battle sprites (src/data/heroSkins.js) can be recoloured to match the art.
// Writes src/data/artPalettes.js. Usage: node scripts/extractPalettes.mjs
import fs from 'node:fs';
import { decodePNG } from './png.mjs';
import { HEROES, MAIN_JOBS } from '../src/data/heroes.js';

const dir = new URL('../assets/cards/', import.meta.url);
const ids = [...HEROES.map((h) => h.id), ...Object.values(MAIN_JOBS).map((j) => j.id)];

const rgbToHsl = (r, g, b) => { r /= 255; g /= 255; b /= 255; const mx = Math.max(r, g, b), mn = Math.min(r, g, b), l = (mx + mn) / 2, d = mx - mn; if (!d) return [0, 0, l]; const s = d / (1 - Math.abs(2 * l - 1)); let h = mx === r ? ((g - b) / d) % 6 : mx === g ? (b - r) / d + 2 : (r - g) / d + 4; h *= 60; if (h < 0) h += 360; return [h, s, l]; };
const hex = (r, g, b) => '#' + [r, g, b].map((v) => Math.round(v).toString(16).padStart(2, '0')).join('');
const isSkin = (h, s, l) => h >= 10 && h <= 45 && s >= 0.15 && s <= 0.75 && l >= 0.55 && l <= 0.92;
const isLine = (l) => l < 0.14;

/** Dominant colour of a region, ignoring background (colours close to the frame's border colour), skin and line art. */
const bucketKey = (r, g, b) => { const [h, s, l] = rgbToHsl(r, g, b); return `${Math.round(h / 12)}:${Math.round(s * 4)}:${Math.round(l * 5)}`; };
/** Colour buckets that appear in the upper corners = background (works for detailed scenery, not just flat fills). */
function backgroundKeys(img) {
  const { width, height, data } = img; const keys = new Map();
  for (const [x0, x1] of [[0, 0.22], [0.78, 1]]) for (let y = 0; y < height * 0.45; y += 3) for (let x = Math.floor(x0 * width); x < Math.floor(x1 * width); x += 3) {
    const i = (y * width + x) * 4; const k = bucketKey(data[i], data[i + 1], data[i + 2]); keys.set(k, (keys.get(k) ?? 0) + 1);
  }
  const total = [...keys.values()].reduce((a, b) => a + b, 0);
  return new Set([...keys.entries()].filter(([, n]) => n > total * 0.01).map(([k]) => k));
}
function dominant(img, x0, y0, x1, y1, bgKeys, opts = {}) {
  const { width, data } = img; const buckets = new Map();
  for (let y = Math.floor(y0 * img.height); y < Math.floor(y1 * img.height); y += 2) for (let x = Math.floor(x0 * width); x < Math.floor(x1 * width); x += 2) {
    const i = (y * width + x) * 4; const r = data[i], g = data[i + 1], b = data[i + 2]; if (data[i + 3] < 200) continue;
    const key = bucketKey(r, g, b); if (bgKeys.has(key)) continue;
    const [h, s, l] = rgbToHsl(r, g, b); if (isLine(l) || (opts.skipSkin && isSkin(h, s, l))) continue;
    if (opts.skipWhite && l > 0.9 && s < 0.2) continue;
    const e = buckets.get(key) ?? { n: 0, r: 0, g: 0, b: 0 }; e.n++; e.r += r; e.g += g; e.b += b; buckets.set(key, e);
  }
  const best = [...buckets.values()].sort((a, b) => b.n - a.n)[0]; if (!best) return null;
  return { hex: hex(best.r / best.n, best.g / best.n, best.b / best.n), n: best.n };
}

const out = {}; let n = 0;
for (const id of ids) {
  const file = new URL(`${id}.png`, dir); if (!fs.existsSync(file)) continue;
  const img = decodePNG(fs.readFileSync(file)); const bgKeys = backgroundKeys(img);
  const def = [...HEROES, ...Object.values(MAIN_JOBS)].find((d) => d.id === id);
  const bald = def?.look?.hair === 'bald';
  const hair = bald ? null : dominant(img, 0.36, 0.1, 0.64, 0.27, bgKeys, { skipSkin: true, skipWhite: true }); // bangs / top of head
  const jacket = dominant(img, 0.22, 0.44, 0.78, 0.72, bgKeys, { skipSkin: true, skipWhite: true });          // torso
  const accent = dominant(img, 0.43, 0.42, 0.57, 0.64, bgKeys, { skipSkin: true, skipWhite: true });          // chest centre (tie / lanyard)
  if (!jacket) { console.log('skip', id); continue; }
  // hair: keep only a convincing colour (not a halo/sky highlight); otherwise the hand palette stays in charge
  const hairOk = hair && (() => { const [r, g, b] = [1, 3, 5].map((i) => parseInt(hair.hex.slice(i, i + 2), 16)); const [, s, l] = rgbToHsl(r, g, b); return l <= 0.78 && !(s < 0.12 && l > 0.6); })();
  out[id] = { ...(hairOk ? { H: hair.hex } : {}), B: jacket.hex, ...(accent && accent.hex !== jacket.hex ? { W: accent.hex } : {}) };
  n++; console.log(id.padEnd(12), 'hair', hair?.hex ?? '(bald)', 'jacket', jacket.hex, 'accent', accent?.hex ?? '-');
}
const src = `// Generated by scripts/extractPalettes.mjs from assets/cards/*.png — hair (H), jacket (B) and chest accent (W)\n// colours of each character's illustration, so battle sprites are recoloured to match the card art.\nexport const ART_PALETTES = ${JSON.stringify(out, null, 2)};\n`;
fs.writeFileSync(new URL('../src/data/artPalettes.js', import.meta.url), src);
console.log(`artPalettes.js: ${n} characters`);
